print("Welcome to DA MONKEY THEME PARK")
print("ARE YOU TALL ENOUGH FOR THE MONSTA RIDE?")
height = input("PLEASE INPUT YOUR HEIGHT (IN CM WITHOUT THE CM SYMBOL), SORRY IF YOU ARE TOO UNWORTHY...")
if height >= "120":
    print("YOU ARE CAPABLE OF RIDING THIS RIDE!!!  HAVE FUN... WEEEEEEEEEEEE....")
if height < "120":
    print("SORRY LITTLE BOI, YOU ARE UNWORTHY...")
else:
    print("UMM.......")
