listy = ["SIGMA","SKIBIDI","MR DAVIES","PROBRABLY GETTING MAD"]
for ["SIGMA","SKIBIDI","MR DAVIES","PROBRABLY GETTING MAD"] in range(2):
    print(["SIGMA","SKIBIDI","MR DAVIES","PROBRABLY GETTING MAD"])
